import { Link } from 'react-router-dom';
import Header from '../components/Header';
import Footer from '../components/Footer';
import { Card } from '../components/ui/card';
import { Button } from '../components/ui/button';
import { Badge } from '../components/ui/badge';
import { Info, Layers, Database, Cpu, ShieldCheck, Code, ArrowRight, Github, ExternalLink } from 'lucide-react';

const About = () => {
  return (
    <div className="flex flex-col min-h-screen bg-background text-foreground font-sans">
      <Header />

      <main className="flex-grow container mx-auto px-4 py-8 md:py-12 max-w-5xl space-y-12">
        {/* Header Title */}
        <div className="text-center max-w-3xl mx-auto space-y-3">
          <Badge variant="outline" className="chip-mono rounded-full border-none bg-[#0071e3]/10 px-3.5 py-1 text-xs font-semibold text-[#0071e3]">
            Engine Blueprint &amp; Philosophy
          </Badge>
          <h1 className="text-3xl md:text-5xl font-extrabold tracking-tight text-[#1d1d1f]">
            About CareerOS
          </h1>
          <p className="text-base text-[#86868b] leading-relaxed">
            An open-spec, event-driven career intelligence platform engineered for zero-latency resume analysis and mathematical RAG matching.
          </p>
        </div>

        {/* Mission Statement Card */}
        <div className="apple-card p-8 md:p-12 space-y-4 bg-gradient-to-b from-white to-[#f5f5f7]">
          <h2 className="text-2xl font-bold text-[#1d1d1f]">Our Core Engineering Philosophy</h2>
          <p className="text-base text-[#424245] leading-relaxed">
            CareerOS was born out of frustration with low-quality, template-heavy "AI slop" wrappers. Most resume analyzers pass raw text directly to an LLM and ask it to guess a score out of 100, resulting in non-deterministic, hallucinatory feedback.
          </p>
          <p className="text-base text-[#424245] leading-relaxed">
            We built CareerOS on **true event-driven engineering principles**: decoupling request ingestion from worker processing, persisting binary objects in S3 storage, calculating mathematical vector distance via <code>pgvector</code>, and using native Web Speech browser APIs for zero-cost live voice interview practice.
          </p>
        </div>

        {/* Technical Architecture Specs Grid */}
        <div className="space-y-6">
          <h2 className="text-2xl font-bold text-[#1d1d1f]">System Architecture Breakdown</h2>

          <div className="grid gap-6 md:grid-cols-2">
            {/* Spec 1 */}
            <div className="apple-card p-6 space-y-3">
              <div className="flex items-center gap-3">
                <div className="flex h-10 w-10 items-center justify-center rounded-xl bg-[#0071e3]/10 text-[#0071e3]">
                  <Database className="h-5 w-5" />
                </div>
                <h3 className="text-base font-bold text-[#1d1d1f]">PostgreSQL + pgvector</h3>
              </div>
              <p className="text-sm text-[#86868b] leading-relaxed">
                Stores candidate data and 768-dimensional float vector embeddings generated by Google Gemini <code>text-embedding-004</code>. Matches candidates using native <code>1 - (v1 &lt;=&gt; v2)</code> cosine similarity queries.
              </p>
            </div>

            {/* Spec 2 */}
            <div className="apple-card p-6 space-y-3">
              <div className="flex items-center gap-3">
                <div className="flex h-10 w-10 items-center justify-center rounded-xl bg-[#34c759]/10 text-[#34c759]">
                  <Layers className="h-5 w-5" />
                </div>
                <h3 className="text-base font-bold text-[#1d1d1f]">BullMQ &amp; Redis Queue</h3>
              </div>
              <p className="text-sm text-[#86868b] leading-relaxed">
                Decouples request ingestion from worker processing. Express handles uploads in &lt;50ms, while background worker nodes execute multi-step parsing and RAG tasks with exponential backoff retries.
              </p>
            </div>

            {/* Spec 3 */}
            <div className="apple-card p-6 space-y-3">
              <div className="flex items-center gap-3">
                <div className="flex h-10 w-10 items-center justify-center rounded-xl bg-[#af52de]/10 text-[#af52de]">
                  <Cpu className="h-5 w-5" />
                </div>
                <h3 className="text-base font-bold text-[#1d1d1f]">MinIO S3 Object Store</h3>
              </div>
              <p className="text-sm text-[#86868b] leading-relaxed">
                Provides stateless binary document persistence in isolated MinIO S3 buckets, eliminating local filesystem disk state and enabling seamless horizontal container scaling.
              </p>
            </div>

            {/* Spec 4 */}
            <div className="apple-card p-6 space-y-3">
              <div className="flex items-center gap-3">
                <div className="flex h-10 w-10 items-center justify-center rounded-xl bg-[#ff9500]/10 text-[#ff9500]">
                  <Code className="h-5 w-5" />
                </div>
                <h3 className="text-base font-bold text-[#1d1d1f]">Web Speech Browser Engine</h3>
                <p className="text-sm text-[#86868b] leading-relaxed">
                  Powers the Live Voice AI Mock Interviewer using Web Speech Recognition (microphone speech-to-text) and Web Speech Synthesis (voice playback) with $0 API audio streaming fees.
                </p>
              </div>
            </div>
          </div>
        </div>

        {/* Developer Spec Link Banner */}
        <div className="apple-card p-8 flex flex-col md:flex-row items-center justify-between gap-6 bg-[#0071e3]/5 border-[#0071e3]/30">
          <div>
            <h3 className="text-lg font-bold text-[#1d1d1f]">Explore the Complete Technical Handbook</h3>
            <p className="text-sm text-[#86868b]">Read the full architectural specification, code flows, and mathematical derivations in our interactive manual.</p>
          </div>
          <a href="/careeros_master_handbook.html" target="_blank" rel="noreferrer">
            <Button className="apple-button h-11 px-5 text-xs font-semibold whitespace-nowrap">
              Open Technical Spec <ExternalLink className="ml-1.5 h-3.5 w-3.5" />
            </Button>
          </a>
        </div>
      </main>

      <Footer />
    </div>
  );
};

export default About;
